"""add is_master and resolution to media_representations

Revision ID: 550f4f50bbb3
Revises: b94662d95377
Create Date: 2026-06-03 09:33:26.676920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550f4f50bbb3'
down_revision: Union[str, Sequence[str], None] = 'b94662d95377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_representations', sa.Column('is_master', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('media_representations', sa.Column('resolution', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('media_representations_media_asset_id_fkey'), 'media_representations', type_='foreignkey')
    op.create_foreign_key(None, 'media_representations', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('original_media_files_media_asset_id_fkey'), 'original_media_files', type_='foreignkey')
    op.create_foreign_key(None, 'original_media_files', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('processing_jobs_media_asset_id_fkey'), 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('streaming_manifests_media_asset_id_fkey'), 'streaming_manifests', type_='foreignkey')
    op.create_foreign_key(None, 'streaming_manifests', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('thumbnails_media_asset_id_fkey'), 'thumbnails', type_='foreignkey')
    op.create_foreign_key(None, 'thumbnails', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thumbnails', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('thumbnails_media_asset_id_fkey'), 'thumbnails', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'streaming_manifests', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('streaming_manifests_media_asset_id_fkey'), 'streaming_manifests', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'processing_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('processing_jobs_media_asset_id_fkey'), 'processing_jobs', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'original_media_files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('original_media_files_media_asset_id_fkey'), 'original_media_files', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'media_representations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('media_representations_media_asset_id_fkey'), 'media_representations', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_column('media_representations', 'resolution')
    op.drop_column('media_representations', 'is_master')
    # ### end Alembic commands ###
