"""changing to softdeletemixin for non user models.

Revision ID: b94662d95377
Revises: dbb90a4cafa0
Create Date: 2026-05-31 13:58:40.243363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b94662d95377'
down_revision: Union[str, Sequence[str], None] = 'dbb90a4cafa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_media_representations_url_slug'), table_name='media_representations')
    op.drop_constraint(op.f('media_representations_media_asset_id_fkey'), 'media_representations', type_='foreignkey')
    op.create_foreign_key(None, 'media_representations', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('media_representations', 'url_slug')
    op.drop_column('media_representations', 'search_vector')
    op.drop_constraint(op.f('original_media_files_media_asset_id_fkey'), 'original_media_files', type_='foreignkey')
    op.create_foreign_key(None, 'original_media_files', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index(op.f('ix_public_processing_jobs_url_slug'), table_name='processing_jobs')
    op.drop_constraint(op.f('processing_jobs_media_asset_id_fkey'), 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('processing_jobs', 'url_slug')
    op.drop_column('processing_jobs', 'search_vector')
    op.drop_index(op.f('ix_public_streaming_manifests_url_slug'), table_name='streaming_manifests')
    op.drop_constraint(op.f('streaming_manifests_media_asset_id_fkey'), 'streaming_manifests', type_='foreignkey')
    op.create_foreign_key(None, 'streaming_manifests', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('streaming_manifests', 'url_slug')
    op.drop_column('streaming_manifests', 'search_vector')
    op.drop_index(op.f('ix_public_thumbnails_url_slug'), table_name='thumbnails')
    op.drop_constraint(op.f('thumbnails_media_asset_id_fkey'), 'thumbnails', type_='foreignkey')
    op.create_foreign_key(None, 'thumbnails', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('thumbnails', 'url_slug')
    op.drop_column('thumbnails', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thumbnails', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.add_column('thumbnails', sa.Column('url_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'thumbnails', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('thumbnails_media_asset_id_fkey'), 'thumbnails', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_public_thumbnails_url_slug'), 'thumbnails', ['url_slug'], unique=False)
    op.add_column('streaming_manifests', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.add_column('streaming_manifests', sa.Column('url_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'streaming_manifests', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('streaming_manifests_media_asset_id_fkey'), 'streaming_manifests', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_public_streaming_manifests_url_slug'), 'streaming_manifests', ['url_slug'], unique=False)
    op.add_column('processing_jobs', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.add_column('processing_jobs', sa.Column('url_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'processing_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('processing_jobs_media_asset_id_fkey'), 'processing_jobs', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_public_processing_jobs_url_slug'), 'processing_jobs', ['url_slug'], unique=False)
    op.drop_constraint(None, 'original_media_files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('original_media_files_media_asset_id_fkey'), 'original_media_files', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.add_column('media_representations', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.add_column('media_representations', sa.Column('url_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'media_representations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('media_representations_media_asset_id_fkey'), 'media_representations', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_public_media_representations_url_slug'), 'media_representations', ['url_slug'], unique=False)
    # ### end Alembic commands ###
