"""creating audit logs table

Revision ID: d4ee3e1ba31f
Revises: 550f4f50bbb3
Create Date: 2026-06-16 21:30:12.766898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ee3e1ba31f'
down_revision: Union[str, Sequence[str], None] = '550f4f50bbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('media_representations_media_asset_id_fkey'), 'media_representations', type_='foreignkey')
    op.create_foreign_key(None, 'media_representations', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('original_media_files_media_asset_id_fkey'), 'original_media_files', type_='foreignkey')
    op.create_foreign_key(None, 'original_media_files', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('processing_jobs_media_asset_id_fkey'), 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('streaming_manifests_media_asset_id_fkey'), 'streaming_manifests', type_='foreignkey')
    op.create_foreign_key(None, 'streaming_manifests', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('thumbnails_media_asset_id_fkey'), 'thumbnails', type_='foreignkey')
    op.create_foreign_key(None, 'thumbnails', 'media_assets', ['media_asset_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thumbnails', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('thumbnails_media_asset_id_fkey'), 'thumbnails', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'streaming_manifests', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('streaming_manifests_media_asset_id_fkey'), 'streaming_manifests', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'processing_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('processing_jobs_media_asset_id_fkey'), 'processing_jobs', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'original_media_files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('original_media_files_media_asset_id_fkey'), 'original_media_files', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'media_representations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('media_representations_media_asset_id_fkey'), 'media_representations', 'media_assets', ['media_asset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
