"""first model initialization

Revision ID: dbb90a4cafa0
Revises: 
Create Date: 2026-05-28 21:15:54.036376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbb90a4cafa0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Enum('video', 'audio', name='media_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'uploaded', 'queued', 'processing', 'ready', 'failed', 'deleted', name='media_asset_status_enum'), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('url_slug', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_media_assets_duration_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_media_assets_base_uuid'), 'media_assets', ['base_uuid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_media_assets_created_at'), 'media_assets', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_assets_deleted_at'), 'media_assets', ['deleted_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_assets_deleted_by'), 'media_assets', ['deleted_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_assets_media_type'), 'media_assets', ['media_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_assets_status'), 'media_assets', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_assets_title'), 'media_assets', ['title'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_assets_updated_at'), 'media_assets', ['updated_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_assets_url_slug'), 'media_assets', ['url_slug'], unique=False, schema='public')
    op.create_table('media_representations',
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=64), nullable=False),
    sa.Column('codec', sa.String(length=64), nullable=False),
    sa.Column('bitrate', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('segment_type', sa.Enum('ts', 'fmp4', name='segment_type_enum'), server_default=sa.text("'fmp4'"), nullable=False),
    sa.Column('playlist_path', sa.String(length=1000), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('url_slug', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bitrate > 0', name='ck_media_representations_bitrate_positive'),
    sa.CheckConstraint('height IS NULL OR height > 0', name='ck_media_representations_height_positive'),
    sa.CheckConstraint('width IS NULL OR width > 0', name='ck_media_representations_width_positive'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['public.media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_path'),
    schema='public'
    )
    op.create_index('ix_media_representations_media_quality', 'media_representations', ['media_asset_id', 'quality'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_representations_base_uuid'), 'media_representations', ['base_uuid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_media_representations_created_at'), 'media_representations', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_representations_deleted_at'), 'media_representations', ['deleted_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_representations_deleted_by'), 'media_representations', ['deleted_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_representations_media_asset_id'), 'media_representations', ['media_asset_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_representations_quality'), 'media_representations', ['quality'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_representations_updated_at'), 'media_representations', ['updated_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_media_representations_url_slug'), 'media_representations', ['url_slug'], unique=False, schema='public')
    op.create_table('original_media_files',
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BIGINT(), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('url_slug', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_original_media_files_size_non_negative'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['public.media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key'),
    schema='public'
    )
    op.create_index(op.f('ix_public_original_media_files_base_uuid'), 'original_media_files', ['base_uuid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_original_media_files_checksum'), 'original_media_files', ['checksum'], unique=False, schema='public')
    op.create_index(op.f('ix_public_original_media_files_created_at'), 'original_media_files', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_original_media_files_deleted_at'), 'original_media_files', ['deleted_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_original_media_files_deleted_by'), 'original_media_files', ['deleted_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_original_media_files_media_asset_id'), 'original_media_files', ['media_asset_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_original_media_files_updated_at'), 'original_media_files', ['updated_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_original_media_files_url_slug'), 'original_media_files', ['url_slug'], unique=False, schema='public')
    op.create_table('processing_jobs',
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('transcode', 'thumbnail', 'waveform', 'subtitle', name='processing_job_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='processing_job_status_enum'), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('url_slug', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name='ck_processing_jobs_progress_range'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['public.media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_processing_jobs_media_asset_status', 'processing_jobs', ['media_asset_id', 'status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_processing_jobs_base_uuid'), 'processing_jobs', ['base_uuid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_processing_jobs_created_at'), 'processing_jobs', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_processing_jobs_deleted_at'), 'processing_jobs', ['deleted_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_processing_jobs_deleted_by'), 'processing_jobs', ['deleted_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_processing_jobs_media_asset_id'), 'processing_jobs', ['media_asset_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_processing_jobs_status'), 'processing_jobs', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_processing_jobs_updated_at'), 'processing_jobs', ['updated_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_processing_jobs_url_slug'), 'processing_jobs', ['url_slug'], unique=False, schema='public')
    op.create_table('streaming_manifests',
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('manifest_type', sa.Enum('hls', 'dash', name='manifest_type_enum'), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('url_slug', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['public.media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key'),
    schema='public'
    )
    op.create_index(op.f('ix_public_streaming_manifests_base_uuid'), 'streaming_manifests', ['base_uuid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_streaming_manifests_created_at'), 'streaming_manifests', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_streaming_manifests_deleted_at'), 'streaming_manifests', ['deleted_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_streaming_manifests_deleted_by'), 'streaming_manifests', ['deleted_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_streaming_manifests_manifest_type'), 'streaming_manifests', ['manifest_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_streaming_manifests_media_asset_id'), 'streaming_manifests', ['media_asset_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_streaming_manifests_updated_at'), 'streaming_manifests', ['updated_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_streaming_manifests_url_slug'), 'streaming_manifests', ['url_slug'], unique=False, schema='public')
    op.create_table('thumbnails',
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('url_slug', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height > 0', name='ck_thumbnails_height_positive'),
    sa.CheckConstraint('width > 0', name='ck_thumbnails_width_positive'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['public.media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key'),
    schema='public'
    )
    op.create_index(op.f('ix_public_thumbnails_base_uuid'), 'thumbnails', ['base_uuid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_thumbnails_created_at'), 'thumbnails', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_thumbnails_deleted_at'), 'thumbnails', ['deleted_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_thumbnails_deleted_by'), 'thumbnails', ['deleted_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_thumbnails_media_asset_id'), 'thumbnails', ['media_asset_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_thumbnails_updated_at'), 'thumbnails', ['updated_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_thumbnails_url_slug'), 'thumbnails', ['url_slug'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_thumbnails_url_slug'), table_name='thumbnails', schema='public')
    op.drop_index(op.f('ix_public_thumbnails_updated_at'), table_name='thumbnails', schema='public')
    op.drop_index(op.f('ix_public_thumbnails_media_asset_id'), table_name='thumbnails', schema='public')
    op.drop_index(op.f('ix_public_thumbnails_deleted_by'), table_name='thumbnails', schema='public')
    op.drop_index(op.f('ix_public_thumbnails_deleted_at'), table_name='thumbnails', schema='public')
    op.drop_index(op.f('ix_public_thumbnails_created_at'), table_name='thumbnails', schema='public')
    op.drop_index(op.f('ix_public_thumbnails_base_uuid'), table_name='thumbnails', schema='public')
    op.drop_table('thumbnails', schema='public')
    op.drop_index(op.f('ix_public_streaming_manifests_url_slug'), table_name='streaming_manifests', schema='public')
    op.drop_index(op.f('ix_public_streaming_manifests_updated_at'), table_name='streaming_manifests', schema='public')
    op.drop_index(op.f('ix_public_streaming_manifests_media_asset_id'), table_name='streaming_manifests', schema='public')
    op.drop_index(op.f('ix_public_streaming_manifests_manifest_type'), table_name='streaming_manifests', schema='public')
    op.drop_index(op.f('ix_public_streaming_manifests_deleted_by'), table_name='streaming_manifests', schema='public')
    op.drop_index(op.f('ix_public_streaming_manifests_deleted_at'), table_name='streaming_manifests', schema='public')
    op.drop_index(op.f('ix_public_streaming_manifests_created_at'), table_name='streaming_manifests', schema='public')
    op.drop_index(op.f('ix_public_streaming_manifests_base_uuid'), table_name='streaming_manifests', schema='public')
    op.drop_table('streaming_manifests', schema='public')
    op.drop_index(op.f('ix_public_processing_jobs_url_slug'), table_name='processing_jobs', schema='public')
    op.drop_index(op.f('ix_public_processing_jobs_updated_at'), table_name='processing_jobs', schema='public')
    op.drop_index(op.f('ix_public_processing_jobs_status'), table_name='processing_jobs', schema='public')
    op.drop_index(op.f('ix_public_processing_jobs_media_asset_id'), table_name='processing_jobs', schema='public')
    op.drop_index(op.f('ix_public_processing_jobs_job_type'), table_name='processing_jobs', schema='public')
    op.drop_index(op.f('ix_public_processing_jobs_deleted_by'), table_name='processing_jobs', schema='public')
    op.drop_index(op.f('ix_public_processing_jobs_deleted_at'), table_name='processing_jobs', schema='public')
    op.drop_index(op.f('ix_public_processing_jobs_created_at'), table_name='processing_jobs', schema='public')
    op.drop_index(op.f('ix_public_processing_jobs_base_uuid'), table_name='processing_jobs', schema='public')
    op.drop_index('ix_processing_jobs_media_asset_status', table_name='processing_jobs', schema='public')
    op.drop_table('processing_jobs', schema='public')
    op.drop_index(op.f('ix_public_original_media_files_url_slug'), table_name='original_media_files', schema='public')
    op.drop_index(op.f('ix_public_original_media_files_updated_at'), table_name='original_media_files', schema='public')
    op.drop_index(op.f('ix_public_original_media_files_media_asset_id'), table_name='original_media_files', schema='public')
    op.drop_index(op.f('ix_public_original_media_files_deleted_by'), table_name='original_media_files', schema='public')
    op.drop_index(op.f('ix_public_original_media_files_deleted_at'), table_name='original_media_files', schema='public')
    op.drop_index(op.f('ix_public_original_media_files_created_at'), table_name='original_media_files', schema='public')
    op.drop_index(op.f('ix_public_original_media_files_checksum'), table_name='original_media_files', schema='public')
    op.drop_index(op.f('ix_public_original_media_files_base_uuid'), table_name='original_media_files', schema='public')
    op.drop_table('original_media_files', schema='public')
    op.drop_index(op.f('ix_public_media_representations_url_slug'), table_name='media_representations', schema='public')
    op.drop_index(op.f('ix_public_media_representations_updated_at'), table_name='media_representations', schema='public')
    op.drop_index(op.f('ix_public_media_representations_quality'), table_name='media_representations', schema='public')
    op.drop_index(op.f('ix_public_media_representations_media_asset_id'), table_name='media_representations', schema='public')
    op.drop_index(op.f('ix_public_media_representations_deleted_by'), table_name='media_representations', schema='public')
    op.drop_index(op.f('ix_public_media_representations_deleted_at'), table_name='media_representations', schema='public')
    op.drop_index(op.f('ix_public_media_representations_created_at'), table_name='media_representations', schema='public')
    op.drop_index(op.f('ix_public_media_representations_base_uuid'), table_name='media_representations', schema='public')
    op.drop_index('ix_media_representations_media_quality', table_name='media_representations', schema='public')
    op.drop_table('media_representations', schema='public')
    op.drop_index(op.f('ix_public_media_assets_url_slug'), table_name='media_assets', schema='public')
    op.drop_index(op.f('ix_public_media_assets_updated_at'), table_name='media_assets', schema='public')
    op.drop_index(op.f('ix_public_media_assets_title'), table_name='media_assets', schema='public')
    op.drop_index(op.f('ix_public_media_assets_status'), table_name='media_assets', schema='public')
    op.drop_index(op.f('ix_public_media_assets_media_type'), table_name='media_assets', schema='public')
    op.drop_index(op.f('ix_public_media_assets_deleted_by'), table_name='media_assets', schema='public')
    op.drop_index(op.f('ix_public_media_assets_deleted_at'), table_name='media_assets', schema='public')
    op.drop_index(op.f('ix_public_media_assets_created_at'), table_name='media_assets', schema='public')
    op.drop_index(op.f('ix_public_media_assets_base_uuid'), table_name='media_assets', schema='public')
    op.drop_table('media_assets', schema='public')
    # ### end Alembic commands ###
